databaseChangeLog:
  - changeSet:
      id: insert-products
      author: minh
      changes:
        - insert:
            tableName: products
            columns:
              - column: { name: id, value: 1 }
              - column: { name: name, value: "Gạo ST25" }
              - column: { name: description, value: "Gạo ngon nhất thế giới" }
              - column: { name: price, value: 25000 }
              - column: { name: stock_quantity, value: 100 }
              - column: { name: unit, value: "kg" }
              - column: { name: created_at, value: "2024-03-01T10:00:00" }
              - column: { name: rice_type, value: 0 }

        - insert:
            tableName: products
            columns:
              - column: { name: id, value: 2 }
              - column: { name: name, value: "Gạo Nàng Hương" }
              - column: { name: description, value: "Mềm dẻo, thơm nhẹ" }
              - column: { name: price, value: 18000 }
              - column: { name: stock_quantity, value: 150 }
              - column: { name: unit, value: "kg" }
              - column: { name: created_at, value: "2024-03-02T15:00:00" }
              - column: { name: rice_type, value: 1 }
